# Generated by Django 3.1.3 on 2020-12-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201218_1210'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='professor_area_conhecimento1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='professorareaconhecimento1', to='base.areaconhecimento', verbose_name='Área do conhecimento'),
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_area_conhecimento2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='professorareaconhecimento2', to='base.areaconhecimento', verbose_name='Área do conhecimento'),
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_area_conhecimento3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='professorareaconhecimento3', to='base.areaconhecimento', verbose_name='Área do conhecimento'),
        ),
    ]
