# Generated by Django 3.1.3 on 2020-11-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipio_codigo', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Código do Município')),
                ('municipio_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('municipio_nome', models.CharField(max_length=50, verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_codigo', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Codigo do País')),
                ('pais_nome', models.CharField(max_length=50, verbose_name='País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
    ]
