# Generated by Django 3.1.3 on 2020-12-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201217_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursofs',
            options={'verbose_name': 'Curso Formação Superior', 'verbose_name_plural': 'Cursos de Formação Superior'},
        ),
    ]
