# Generated by Django 3.1.3 on 2021-01-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210128_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='municipio_codigo',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Código do Município'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais_codigo',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Código do País'),
        ),
    ]
