# Generated by Django 3.1.3 on 2020-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201217_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('area_codigo', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Código da componente curricular')),
                ('componente_curricular', models.CharField(max_length=50, unique=True, verbose_name='Componente curricular')),
                ('area_conhecimento', models.CharField(max_length=50, verbose_name='Área de conhecimento')),
            ],
        ),
        migrations.RenameField(
            model_name='cursofs',
            old_name='cfs_id',
            new_name='cfs_codigo',
        ),
    ]
