# Generated by Django 3.1.3 on 2021-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210128_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeComplementar',
            fields=[
                ('codigo_area', models.CharField(max_length=2, verbose_name='Código da área')),
                ('nome_area', models.CharField(max_length=50, verbose_name='Nome da área')),
                ('codigo_subarea', models.CharField(max_length=3, verbose_name='Código da sub-área')),
                ('nome_subarea', models.CharField(max_length=50, verbose_name='Nome da área')),
                ('codigo_atividade', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Código da atividade')),
                ('nome_atividade', models.CharField(max_length=100, verbose_name='Nome da atividade')),
            ],
            options={
                'verbose_name': 'Atividade complementar',
                'verbose_name_plural': 'Atividades complementares',
                'ordering': ['codigo_area', 'codigo_subarea', 'nome_atividade'],
            },
        ),
    ]
