# Generated by Django 3.1.3 on 2020-12-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201218_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaconhecimento',
            options={'ordering': ['area_conhecimento'], 'verbose_name': 'Área de conhecimento', 'verbose_name_plural': 'Áreas de conhecimento'},
        ),
    ]
