# Generated by Django 3.1.3 on 2020-12-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201223_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaconhecimento',
            options={'ordering': ['componente_curricular'], 'verbose_name': 'Componente curricular', 'verbose_name_plural': 'Componentes curriculares'},
        ),
    ]
