# Generated by Django 5.0.6 on 2024-07-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_nome', models.CharField(choices=[('port', 'Português'), ('ingl', 'Inglês'), ('espa', 'Espanhol'), ('mate', 'Matemática'), ('cien', 'Ciências'), ('hist', 'História'), ('arte', 'Artes'), ('geog', 'Geografia'), ('filo', 'Filosofia'), ('edfi', 'Educação Física'), ('enre', 'Ensino Religioso')], max_length=20, verbose_name='Disciplina')),
                ('disciplina_professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinaprofessor', to='professores.professor', verbose_name='Professor(a)')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['disciplina_nome', 'disciplina_professor'],
            },
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.UniqueConstraint(fields=('disciplina_nome', 'disciplina_professor'), name='unica_disciplina_professor'),
        ),
    ]
