# Generated by Django 3.1.3 on 2021-02-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210226_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapabasico',
            options={'ordering': ['etapa_basico_ano', 'etapa_basico_nome'], 'verbose_name': 'Etapa Educação Básica', 'verbose_name_plural': 'Etapas Educação Básica'},
        ),
        migrations.AlterField(
            model_name='anoescolar',
            name='ano_escolar_etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.etapabasico', verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='anoescolar',
            name='ano_escolar_nome',
            field=models.CharField(choices=[('CR', 'Creche'), ('G1', 'Maternal I'), ('G2', 'Maternal II'), ('G3', 'Maternal III'), ('G4', 'Jardim I'), ('G5', 'Jardim II'), ('1A', '1º Ano'), ('2A', '2º Ano'), ('3A', '3º Ano'), ('4A', '4º Ano'), ('5A', '5º Ano'), ('6A', '6º Ano'), ('7A', '7º Ano'), ('8A', '8º Ano'), ('9A', '9º Ano')], max_length=2, verbose_name='Ano escolar'),
        ),
        migrations.AlterField(
            model_name='etapabasico',
            name='etapa_basico_ano',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='principal.anoletivo', verbose_name='Ano Letivo'),
        ),
    ]
