# Generated by Django 3.1.3 on 2021-03-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('principal', '0002_auto_20210303_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anoescolar',
            name='ano_escolar_etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anoescolaretapa', to='principal.etapabasica', verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='disciplina_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disciplinaprofessor', to='professores.professor', verbose_name='Professor(a)'),
        ),
        migrations.AlterField(
            model_name='etapabasica',
            name='etapa_basica_ano',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='etapabasicanome', to='principal.anoletivo', verbose_name='Ano Letivo'),
        ),
    ]
