# Generated by Django 3.1.3 on 2021-03-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('principal', '0003_auto_20210306_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='disciplina_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinaprofessor', to='professores.professor', verbose_name='Professor(a)'),
        ),
    ]
