# Generated by Django 5.0.6 on 2024-07-06 21:15

import base.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('base', '0001_initial'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('turma_id', models.AutoField(primary_key=True, serialize=False)),
                ('turma_ano_escolar', models.CharField(choices=[('CR', 'Creche'), ('G1', 'Maternal I'), ('G2', 'Maternal II'), ('G3', 'Maternal III'), ('G4', 'Jardim I'), ('G5', 'Jardim II'), ('1A', '1º Ano'), ('2A', '2º Ano'), ('3A', '3º Ano'), ('4A', '4º Ano'), ('5A', '5º Ano'), ('6A', '6º Ano'), ('7A', '7º Ano'), ('8A', '8º Ano'), ('9A', '9º Ano')], max_length=2, verbose_name='Ano Escolar')),
                ('turma_nome', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Nome')),
                ('turma_etapa_basica', models.CharField(choices=[('IN', 'Infantil'), ('F1', 'Fundamental I'), ('F2', 'Fundamental II'), ('EM', 'Ensino Médio')], max_length=2, verbose_name='Etapa Básica')),
                ('turma_ano_letivo', models.CharField(max_length=4, validators=[base.validators.validate_digits, base.validators.validate_ano_letivo], verbose_name='Ano Letivo')),
                ('turma_mediacao_pedagogica', models.CharField(choices=[('1', 'Presencial'), ('2', 'Semipresencial'), ('3', 'Educação a distância')], default='1', max_length=2, verbose_name='Mediação didático-pedagógica')),
                ('turma_hora_inicial', models.CharField(choices=[('07:30', '07:30'), ('13:00', '13:00')], max_length=5, verbose_name='Hora Inicial')),
                ('turma_hora_final', models.CharField(choices=[('12:00', '12:00'), ('17:15', '17:15')], max_length=5, verbose_name='Hora final')),
                ('turma_segunda', models.CharField(blank=True, max_length=1, null=True, verbose_name='Segunda')),
                ('turma_terca', models.CharField(blank=True, max_length=1, null=True, verbose_name='Terça')),
                ('turma_quarta', models.CharField(blank=True, max_length=1, null=True, verbose_name='Quarta')),
                ('turma_quinta', models.CharField(blank=True, max_length=1, null=True, verbose_name='Quinta')),
                ('turma_sexta', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexta')),
                ('turma_sabado', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sábado')),
                ('turma_domingo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Domingo')),
                ('turma_escolarizacao', models.CharField(blank=True, max_length=1, null=True, verbose_name='Escolarizacao')),
                ('turma_atividade_complementar', models.CharField(blank=True, max_length=1, null=True, verbose_name='Atividade complementar')),
                ('turma_atendimento_especializado', models.CharField(blank=True, max_length=1, null=True, verbose_name='Atendimento educacional specializado')),
                ('turma_local_diferenciado', models.CharField(choices=[('0', 'Não está em local diferenciado'), ('1', 'Sala anexa'), ('2', 'Unidade de atendimento socioeducativa'), ('3', 'Unidade Prisional')], default='0', max_length=1, verbose_name='Local de funcionamento diferenciado')),
                ('turma_modalidade', models.CharField(choices=[('1', 'Ensino regular'), ('2', 'Educação especial'), ('3', 'Educação de jovens e adultos (EJA)'), ('4', 'Educação profissional')], default=1, max_length=1, verbose_name='Modalidade')),
                ('turma_aluno', models.ManyToManyField(related_name='turmaaluno', to='alunos.aluno', verbose_name='Alunos')),
                ('turma_atividade_complementar_codigo_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividadecomplementarcodigo1', to='base.atividadecomplementar', verbose_name='Atividade complementar código 1')),
                ('turma_atividade_complementar_codigo_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividadecomplementarcodigo2', to='base.atividadecomplementar', verbose_name='Atividade complementar código 2')),
                ('turma_atividade_complementar_codigo_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividadecomplementarcodigo3', to='base.atividadecomplementar', verbose_name='Atividade complementar código 3')),
                ('turma_atividade_complementar_codigo_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividadecomplementarcodigo4', to='base.atividadecomplementar', verbose_name='Atividade complementar código 4')),
                ('turma_atividade_complementar_codigo_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividadecomplementarcodigo5', to='base.atividadecomplementar', verbose_name='Atividade complementar código 5')),
                ('turma_atividade_complementar_codigo_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividadecomplementarcodigo6', to='base.atividadecomplementar', verbose_name='Atividade complementar código 6')),
                ('turma_disciplina', models.ManyToManyField(related_name='turmadisciplinas', to='principal.disciplina', verbose_name='Disciplinas')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-turma_ano_letivo', 'turma_ano_escolar', 'turma_nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('turma_ano_escolar', 'turma_nome', 'turma_ano_letivo'), name='unica_turma_ano'),
        ),
    ]
