# Generated by Django 3.1.3 on 2021-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma_quarta',
            field=models.CharField(max_length=1, verbose_name='Quarta'),
        ),
    ]
