# Generated by Django 3.1.3 on 2021-03-06 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210306_0742'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': [], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AddField(
            model_name='turma',
            name='turma_nome',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma_ano_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='turmaanoescolar', to='principal.anoescolar', verbose_name='Ano Escolar'),
        ),
    ]
