# Generated by Django 3.1.2 on 2021-06-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_auto_20210607_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma_domingo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Domingo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma_quarta',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Quarta'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma_quinta',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Quinta'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma_sabado',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sábado'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma_segunda',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Segunda'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma_sexta',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexta'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma_terca',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Terça'),
        ),
    ]
